
// Even Fibonacci numbers
/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Q2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int fs=1;  
		int sn=2;   
		int sum=0;
		int evensum=0;
		
		while(sum<4000000) {          
			sum=fs+sn;        
			fs=sn;
			sn=sum;
			
			if(sum%2==0) {
				evensum+=sum;
			}
		}
		System.out.println(evensum);
		

	}

}

//OUTPUT: 4613730
